app = "sales-ci-mcp"          # name you chose during fly launch
primary_region = "sin"        # or your region

[build]
  dockerfile = "Dockerfile"

[experimental]
  cmd = ["python", "main.py"]

[[services]]
  internal_port = 8000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 8000
    handlers = ["http"]